# Basic info
replicaCount: 1

image:
  repository: streamreactor/redis
  tag: 1.2.1.7
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

# Monitoring
monitoring:
  pipeline: "test-redis"
  enabled: true
  port: 9102
  path: "/metrics"

podManagementPolicy: OrderedReady

kafka:
  replicationFactor: 1
  bootstrapServers: 
    - name: kafka
      port: 9092
  image:
    repository: landoop/fast-data-dev
    tag: 2.0.0
    pullPolicy: IfNotPresent

schemaRegistries:
  enabled: true
  hosts:
    - host: kafka
      protocol: http
      port: 8081
      jmxPort: 9582 

secretsProvider: env

# javaHeap options    
javaHeap: 256M

# clusterName The connect cluster name. This is the consumer group id for the backing topics
clusterName: "redis-test"

# restPort The rest port of Connect
restPort: "8083"

# logLevel The log4j level
logLevel: INFO

# keyConverter The key converter to/from Connects struct
keyConverter: "io.confluent.connect.avro.AvroConverter"

# valueConverter The key converter to/from Connects struct
valueConverter: "io.confluent.connect.avro.AvroConverter"

# connectorClass
connectorClass: "com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector"

# applicationId name of the connector
applicationId: "test-redis-sink"

# topics to sink
topics: "redis-sink"

# kcql KCQL expression describing field selection and routes. type: STRING importance: HIGH
kcql: "SELECT firstName, lastName, salary from redis-sink PK lastName"

# contact points
host: "redis"

# redis port
port: "6379"

# redis password
password: "redis"

# maxRetries The maximum number of times to try the write again. type: INT importance: MEDIUM
maxRetries: 20

# retryInterval The time in milliseconds between retries. type: INT importance: MEDIUM
retryInterval: 60000

# errorPolicy Specifies the action to be taken if an error occurs while inserting the data.
errorPolicy: THROW

# enabled Enables the output for how many records have been processed type: BOOLEAN importance: MEDIUM
progressEnabled: true